### ISSUE TITLE
When using PerformanceCounters and SQL persistence in one project NServiceBus throws an exception: ScriptBuilderTask task was not given a value for the required parameter "References"

### ISSUE THREAD

**Issue by ismaelhamed** [Particular/NServiceBus.Persistence.Sql#220]
When adding NServiceBus.Persistence.Sql.MsBuild to a project where a reference to the package NServiceBus.Metrics.PerformanceCounters.MsBuild already  exists, I get:

```
The "ScriptBuilderTask" task was not given a value for the required parameter "References"
The "References" parameter is not supported by the "ScriptBuilderTask" task. Verify the parameter exists on the task, and it is a settable public instance property.
```

**Comment by weralabaj** [comment]
Thanks @ismaelhamed for raising it, I'll investigate this issue today.

**Comment by weralabaj** [comment]
We've found the cause of the problem, we have a couple of possible solutions.

@ismaelhamed Can you tell me if that issue is blocking for you? Are you using this in production/existing solution or is it more like POC/test scenario and it's not as urgent?

**Comment by Scooletz** [comment]
Ping @Particular/metrics-maintainers We should take a look at it.

**Comment by ismaelhamed** [comment]
@weralabaj definitely not a blocking issue: I'm just trying out the new persistence

**Comment by weralabaj** [comment]
We're discussing internally how to best go about it. I think right now the most likely outcome is releasing new minor versions for both `NServiceBus.Persistence.Sql.MsBuild` and `NServiceBus.Metrics.PerformanceCounters.MsBuild`. I'll keep you updated!

**Comment by weralabaj** [comment]
Fixed and smoke tested in releases 2.2 and 1.0.6

**Comment by weralabaj** [comment]
@ismaelhamed  The fix is included in releases 1.0.6 and 2.2.0, just published. Details [here](https://github.com/Particular/NServiceBus.Persistence.Sql/releases/tag/1.0.6) and [here](https://github.com/Particular/NServiceBus.Persistence.Sql/releases/tag/2.2.0).

**Comment by ismaelhamed** [comment]
@weralabaj, still fails to compile:
```
The "NServiceBus.Metrics.PerformanceCounters.ScriptBuilderTask" task could not be loaded from the assembly C:\Projects\nsb6\src\packages\NServiceBus.Persistence.Sql.MsBuild.2.2.0\build\..\netclassic\NServiceBus.Persistence.Sql.ScriptBuilderTask.dll. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
```
Above error may reference `SqlPersistenceScriptBuilderTask` in `NServiceBus.Metrics.PerformanceCounters.Task.dll` instead, depending on which MSBuild package I add first.

**Comment by weralabaj** [comment]
Seems like it's still looking in the wrong assembly, i.e. for performancecounters task in the sql persistence assembly ;) I've had a bit different issue, but I think the cause is the same.  Seems that Nuget is a bit too aggressive with caching/storing packages locally and even though you referenced new packages, it still loads some of the old code that is getting confused by the task name duplication.

It should help if you remove the contents of `C:\Users\`**your_user_name**`\.nuget\packages\nservicebus.persistence.sql.msbuild\` and `C:\Users\`**your_user_name**`\.nuget\packages\nservicebus.metrics.performancecounters.msbuild` and clean the project.

Can you try this?

**Comment by Scooletz** [comment]
@ismaelhamed If you faced the problem again, after cleaning proposed by @weralabaj , could you share with us the project you're working on? Just to make the bug reproducible.

**Comment by bording** [comment]
Another thing to watch out for is that since Visual Studio loads task assemblies into memory, if you update a package that contains a new version of a task assembly, the new version likely won't be used until you restart Visual Studio, giving it a chance to load the new version of the assembly.

**Comment by ismaelhamed** [comment]
@weralabaj @Scooletz @bording Sorry but I tried everything and still couldn't get it to compile. So I just started from a blank slate and I can confirm the same issue:

1. Create new console application
2. Add package `NServiceBus.Metrics.PerformanceCounters.MsBuild`
3. Compile (fine)
4. Add package `NServiceBus.Persistence.Sql.MsBuild`
5. Compile (failed):

```
The "NServiceBus.Metrics.PerformanceCounters.ScriptBuilderTask" task could not be loaded from the assembly C:\source\repos\msbuild-sample\packages\NServiceBus.Persistence.Sql.MsBuild.2.2.0\build\..\netclassic\NServiceBus.Persistence.Sql.ScriptBuilderTask.dll.  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.		
```

**Comment by bording** [comment]
@ismaelhamed I'm able to repro the problem as well. You're correct that there is still something not right here. I'm investigating now.

**Comment by bording** [comment]
OK, it looks like we've got more changes to make to get this working. I'm going to re-open this bug because it is not fixed.

**Comment by weralabaj** [comment]
I see that my testing flow was a bit different, although sometimes it worked right away, sometimes I needed an additional step to get it running, i.e.:
6. Remove nuget packages from `C:\Users\`**user**`\.nuget\packages\nservicebus.persistence.sql`, `C:\Users\`**user**`\.nuget\packages\nservicebus.persistence.sql.msbuild`. Also a couple of times that wasn't enough, then I had to also delete all content from `C:\Users\`**user**`\.nuget\packages\nservicebus.metrics.performancecounters` and `C:\Users\`**user**`\.nuget\packages\nservicebus.metrics.performancecounters.msbuild`.

**Comment by weralabaj** [comment]
Hi @ismaelhamed I've just released patches - 2.2.1 and 1.0.7.

After talking to Brandon we've found out that my testing protocol was flawed, I was "lucky" to base my testing on an edge-case scenario that was indeed working :) This time the testing was more comprehensive, so I believe we covered all the aspects of the problem.

**Comment by ismaelhamed** [comment]
@weralabaj @bording Thanks, I can confirm the issue has been resolved.
