### ISSUE TITLE
FeedBack - Version 3 release from an NSB v7 beta user perspective

### ISSUE THREAD

**Issue by gbiellem** [Particular/NServiceBus.Persistence.Sql#233]
Hi Particles

Great to see the PostgreSQL support in the latest release.

I do have some minor gripes about the release though that I thought I'd share:

- Since you had a beta of v3.x that targetted NSBv7 it's a bit of smell to release a final that targets  NSB v6.   Surely this could have been a 2.x.  What was the breaking change?

- Since you've bumped the major of the stable version it would have been nice if you also pushed the corresponding beta release for V7 users to Nuget.  Currently our builds are setup to using wildcards for the beta nugets so we are using the latest.  This release broke those builds and to fix them I have to hard code a beta release rather than bumping the major to v4.  I know there is a V4 on your MyGET feed but not all users can or want to use that feed.

- The doco is also messed up now,  For instance take a look at https://docs.particular.net/search?q=persistence.  You'll see V3.x listed under the NSB 7.x results and V4.x is listed under V6.

**Comment by SzymonPobiega** [comment]
Thanks for the feedback @gbiellem . I'll push the 4.0.0-beta1 today. The doco PR should also be merged today.

We has one breaking change when we decided to support PostgreSQL for 6, that's why it was not possible to release 2.3 :(

**Comment by SzymonPobiega** [comment]
@gbiellem I've pushed `4.0.0-beta0001` to nuget. Sorry for the inconvenience. I've dropped the ball yesterday.

The doco should also be fixed now.

**Comment by gbiellem** [comment]
Cool.  Thanks @SzymonPobiega.  Looking forward to RC :)

**Comment by gbiellem** [comment]
@SzymonPobiega, you missed something.   The 4.0 beta1 relies on NSB 7 beta12 which isn't on nuget.

**Comment by SzymonPobiega** [comment]
@gbiellem we're trying to solve it. Probably by pushing Beta12

**Comment by SzymonPobiega** [comment]
@gbiellem due to some issues with core we're changing plans and will be releasing SQLP 4.0-beta2 that targets core beta8

**Comment by SzymonPobiega** [comment]
@gbiellem 4.0.0-beta2 which targets NSB beta8 is out. Sorry for the problem.

**Comment by gbiellem** [comment]
Thanks @SzymonPobiega  - will upgrade in the morning

**Comment by gbiellem** [comment]
Thanks again @SzymonPobiega  -we are now on v4 beta 2
